#!/bin/bash
cmake \
  -DENABLE_SOLVER_STP=ON \
  -DENABLE_SOLVER_Z3=ON \
  -DENABLE_POSIX_RUNTIME=ON \
  -DENABLE_KLEE_UCLIBC=ON \
  -DKLEE_UCLIBC_PATH=/home/jjf/work_env/klee/klee-uclibc \
  -DENABLE_UNIT_TESTS=ON \
  -DGTEST_SRC_DIR=/home/jjf/work_env/klee/googletest-release-1.7.0 \
  -DLLVM_CONFIG_BINARY=/usr/bin/llvm-config-9 \
  -DLLVMCC=/usr/bin/clang-9 \
  -DLLVMCXX=/usr/bin/clang++-9 \
  -DENABLE_KLEE_LIBCXX=ON -DKLEE_LIBCXX_DIR=/usr/local/jjf/libc++-install-9/ -DKLEE_LIBCXX_INCLUDE_DIR=/usr/local/jjf/libc++-install-9/include/c++/v1/ \
  ..
