#!/bin/bash
git clone https://github.com/klee/klee.git
cd klee

# Merge in pending pull requests: welcome to the bleeding edge!
git remote add reid   https://github.com/alastairreid/klee.git
git remote add nowack https://github.com/MartinNowack/klee.git
git fetch --all
git merge nowack/handle_global_variables reid/lazy_intrinsic_rejection

mkdir build
cd build
cmake \
  -DENABLE_SOLVER_STP=ON \
  -DLLVMCC=`which clang` \
  -DENABLE_KLEE_UCLIBC=OFF \
  -DLLVM_CONFIG_BINARY=`ls $HOME/rust/build/x86_*/llvm/bin/llvm-config` \
  -DENABLE_UNIT_TESTS=ON \
  -DGTEST_SRC_DIR=$HOME/klee/googletest-release-1.7.0 \
  ..
make -j20
make check
make install
